In [1]:
%load_ext tensorboard
import tensorflow as tf
import numpy as np
from datetime import datetime
from tensorflow import keras
from tensorflow.estimator import LinearRegressor
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
print(tf.__version__)

2.0.0


In [2]:
# Creating data
X_train = (np.random.sample((10000,5)))
y_train =  (np.random.sample((10000,1)))
X_train.shape
print(X_train)

[[0.90730057 0.58843604 0.71909037 0.22863855 0.58645826]
 [0.92431261 0.21119451 0.68678073 0.34676195 0.38819633]
 [0.29264479 0.05791657 0.81386342 0.89028274 0.04053572]
 ...
 [0.18287633 0.14446028 0.10950957 0.30164347 0.85508766]
 [0.77306417 0.40583277 0.780145   0.51367393 0.03414424]
 [0.02025674 0.13293375 0.39547481 0.03361208 0.7120752 ]]


In [3]:
# Build the tf.keras.Sequential model by stacking layers.
model = tf.keras.models.Sequential([
  #tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(256, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(256, activation='relu'),
  tf.keras.layers.Dense(10, activation='softmax')
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
logdir="logs/fit/" + datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = keras.callbacks.TensorBoard(log_dir=logdir)

In [4]:
# Train the estimator
model.fit(X_train, y_train, epochs=10, callbacks=[tensorboard_callback])

Train on 10000 samples
Epoch 1/10
10000/10000 [==============================] - 2s 242us/sample - loss: 0.0751 - accuracy: 0.0000e+00
Epoch 2/10
10000/10000 [==============================] - 1s 137us/sample - loss: 1.1986e-05 - accuracy: 0.0000e+00
Epoch 3/10
10000/10000 [==============================] - 1s 139us/sample - loss: 4.1520e-06 - accuracy: 0.0000e+00
Epoch 4/10
10000/10000 [==============================] - 1s 135us/sample - loss: 2.1269e-06 - accuracy: 0.0000e+00
Epoch 5/10
10000/10000 [==============================] - 2s 174us/sample - loss: 1.8731e-06 - accuracy: 0.0000e+00
Epoch 6/10
10000/10000 [==============================] - 2s 163us/sample - loss: 7.9891e-07 - accuracy: 0.0000e+00
Epoch 7/10
10000/10000 [==============================] - 2s 196us/sample - loss: 8.1479e-07 - accuracy: 0.0000e+00
Epoch 8/10
10000/10000 [==============================] - 2s 187us/sample - loss: 7.0575e-07 - accuracy: 0.0000e+00
Epoch 9/10
10000/10000 [=============================

In [5]:
model.evaluate(X_train, y_train)

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[1.704664086830121e-08, 0.0]

In [6]:
%tensorboard --logdir logs